sudo: required
services:
  - docker

before_install:
  - docker build -t lokesh40/docker-react -f Dockerfile.dev .

#script:
#  - docker run lokesh40/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-travis-app"
  env: "DockerTravisApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-321873736431"
  bucket_path: "docker-travis-app"
  on:
    branch: master
  access_key_id: $AccessKeyID
  secret_access_key:
    secure: "$AWSsecretID"
